[package]
name = "allow-privilege-escalation-psp"
version = "0.1.11"
authors = ["Flavio Castelli <fcastelli@suse.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
k8s-openapi = { version = "0.14.0", default_features = false, features = ["v1_23"] }
serde_json = "1.0"
wapc-guest = "1.0.0"
kubewarden-policy-sdk = "0.4.2"

[dev-dependencies]
serde_yaml = "0.8"
